# Site settings
title:          Li Jinhao Blog
description:    "Minimal Jekyll theme"
url:            "https://nice01qc.github.io"

# Author
author:
  name:         Li Jinhao 
  url:          https://nice01qc.github.io
  email:        734522310@qq.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       8
