# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/tale"
url:            "https://nice01qc.github.io"

# Author
author:
  name:         Jinhao Li
  url:          https://nice01qc.github.io
  email:        734522310@qq.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
